### PR TITLE
Retry on failure

### PR DESCRIPTION
**Pull request by mrcaseb**
Creating a draft PR because I am unsure if this is a good idea. Various gh workflows are failing randomly because the upload fails. Retrying on failure should be more robust. 

Let's discuss this later.

### CODE REVIEW

**Comment by tanho63** [comment]
Would do it like we do memoise

**Comment by mrcaseb** [comment]
> I would do it like we do memoise

You mean by adding options to activate/deactivate insistent behavior?

**Comment by tanho63** [comment]
maybe environment variables, those would be easier to use in GitHub actions

**Comment by mrcaseb** [comment]
Defaults to non-insistent behavior now which seems like the logical default but we'll have to update all gh workflows with the new env variable

**Comment by tanho63** [comment]
Hmm. Maybe default true better and we can turn off if bork?

**Comment by tanho63** [comment]
LGTM, feel free to merge when ready

**Comment by mrcaseb** [comment]
I'll merge and we will see how many workflows fail lol

**Pull request merged**
