### PR TITLE
format timestamp as character

### PR DESCRIPTION
**Pull request by mrcaseb**
update docs
run code styler

### CODE REVIEW

**Comment by mrcaseb** [comment]
This probably breaks nflreadr's print method. I think the method assumes posix and therefore doesn't format the timestamp in local timezone

**Comment by mrcaseb** [comment]
https://github.com/nflverse/nflreadr/pull/250 required before merging this PR

**Comment by mrcaseb** [comment]
These are all assets we have to update with a string stimestamp
``` r
parquet_assets <- piggyback::pb_list(repo = "nflverse/nflverse-data", .token = gh::gh_token()) |> 
  dplyr::filter(stringr::str_detect(file_name, ".parquet"))
gt::gt_preview(parquet_assets)
```

<div id="xzxniutfdo" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id=""></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="file_name">file_name</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="size">size</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="timestamp">timestamp</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="tag">tag</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="owner">owner</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="repo">repo</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><th id="stub_1_1" scope="row" class="gt_row gt_right gt_stub" style="font-family: Courier;">1</th>
<td headers="stub_1_1 file_name" class="gt_row gt_left">ftn_charting_2022.parquet</td>
<td headers="stub_1_1 size" class="gt_row gt_right">503808</td>
<td headers="stub_1_1 timestamp" class="gt_row gt_right">2024-01-24 14:37:31</td>
<td headers="stub_1_1 tag" class="gt_row gt_left">ftn_charting</td>
<td headers="stub_1_1 owner" class="gt_row gt_left">nflverse</td>
<td headers="stub_1_1 repo" class="gt_row gt_left">nflverse-data</td></tr>
    <tr><th id="stub_1_2" scope="row" class="gt_row gt_right gt_stub" style="font-family: Courier;">2</th>
<td headers="stub_1_2 file_name" class="gt_row gt_left">ftn_charting_2023.parquet</td>
<td headers="stub_1_2 size" class="gt_row gt_right">569478</td>
<td headers="stub_1_2 timestamp" class="gt_row gt_right">2024-02-16 18:13:08</td>
<td headers="stub_1_2 tag" class="gt_row gt_left">ftn_charting</td>
<td headers="stub_1_2 owner" class="gt_row gt_left">nflverse</td>
<td headers="stub_1_2 repo" class="gt_row gt_left">nflverse-data</td></tr>
    <tr><th id="stub_1_3" scope="row" class="gt_row gt_right gt_stub" style="font-family: Courier;">3</th>
<td headers="stub_1_3 file_name" class="gt_row gt_left">qbr_season_level.parquet</td>
<td headers="stub_1_3 size" class="gt_row gt_right">74234</td>
<td headers="stub_1_3 timestamp" class="gt_row gt_right">2024-02-29 09:20:20</td>
<td headers="stub_1_3 tag" class="gt_row gt_left">espn_data</td>
<td headers="stub_1_3 owner" class="gt_row gt_left">nflverse</td>
<td headers="stub_1_3 repo" class="gt_row gt_left">nflverse-data</td></tr>
    <tr><th id="stub_1_4" scope="row" class="gt_row gt_right gt_stub" style="font-family: Courier;">4</th>
<td headers="stub_1_4 file_name" class="gt_row gt_left">qbr_week_level.parquet</td>
<td headers="stub_1_4 size" class="gt_row gt_right">266159</td>
<td headers="stub_1_4 timestamp" class="gt_row gt_right">2024-02-29 09:20:47</td>
<td headers="stub_1_4 tag" class="gt_row gt_left">espn_data</td>
<td headers="stub_1_4 owner" class="gt_row gt_left">nflverse</td>
<td headers="stub_1_4 repo" class="gt_row gt_left">nflverse-data</td></tr>
    <tr><th id="stub_1_5" scope="row" class="gt_row gt_right gt_stub" style="font-family: Courier;">5</th>
<td headers="stub_1_5 file_name" class="gt_row gt_left">roster_weekly_2002.parquet</td>
<td headers="stub_1_5 size" class="gt_row gt_right">344387</td>
<td headers="stub_1_5 timestamp" class="gt_row gt_right">2023-09-06 17:08:46</td>
<td headers="stub_1_5 tag" class="gt_row gt_left">weekly_rosters</td>
<td headers="stub_1_5 owner" class="gt_row gt_left">nflverse</td>
<td headers="stub_1_5 repo" class="gt_row gt_left">nflverse-data</td></tr>
    <tr><th id="stub_1_6" scope="row" class="gt_row gt_right gt_stub" style="font-family: Courier; font-size: x-small; background-color: #E4E4E4;">6..409</th>
<td headers="stub_1_6 file_name" class="gt_row gt_left" style="background-color: #E4E4E4;"></td>
<td headers="stub_1_6 size" class="gt_row gt_right" style="background-color: #E4E4E4;"></td>
<td headers="stub_1_6 timestamp" class="gt_row gt_right" style="background-color: #E4E4E4;"></td>
<td headers="stub_1_6 tag" class="gt_row gt_left" style="background-color: #E4E4E4;"></td>
<td headers="stub_1_6 owner" class="gt_row gt_left" style="background-color: #E4E4E4;"></td>
<td headers="stub_1_6 repo" class="gt_row gt_left" style="background-color: #E4E4E4;"></td></tr>
    <tr><th id="stub_1_7" scope="row" class="gt_row gt_right gt_stub" style="font-family: Courier;">410</th>
<td headers="stub_1_7 file_name" class="gt_row gt_left">combine.parquet</td>
<td headers="stub_1_7 size" class="gt_row gt_right">346816</td>
<td headers="stub_1_7 timestamp" class="gt_row gt_right">2024-03-12 17:14:28</td>
<td headers="stub_1_7 tag" class="gt_row gt_left">combine</td>
<td headers="stub_1_7 owner" class="gt_row gt_left">nflverse</td>
<td headers="stub_1_7 repo" class="gt_row gt_left">nflverse-data</td></tr>
  </tbody>
  &#10;  
</table>
</div>

<sup>Created on 2024-08-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Review by tanho63 — APPROVED** [review]

**Comment by mrcaseb** [comment]
I have updated all PBP parquet files and no problems as of now. So I don't touch other assets until we run into problems

**Pull request merged**
